### PR TITLE
upgrade to 1.21-pre4

### PR DESCRIPTION
**Pull request by Meshiest**
Very minor changes were needed to port to 1.21-pre4

I also included a refactor to change the mod into a client mod and refactored the HudRenderMixin into a HudRenderCallback

for the lazy: you can find a download on my fork's [releases page](https://github.com/Meshiest/reacharound/releases/tag/1.21-pre4)

### CODE REVIEW

**Comment by Vieur** [comment]
Hello, can you also port this to 1.20.6?

**Comment by Meshiest** [comment]
> Hello, can you also port this to 1.20.6?

@Vieur I built a 1.20.6 version on [this branch](https://github.com/Meshiest/reacharound/tree/1.20.6) w/ [this release](https://github.com/Meshiest/reacharound/releases/tag/1.20.6). the only real difference is that the `tickCounter.getTickDelta` in v1.21 is just a deltaTime in v1.20. I was testing some other changes (removal of the hud mixin, switching to a client mod) that shouldn't introduce any bugs (or haven't in my limited testing)

**Comment by spAnser** [comment]
Thanks for the pre-release. I've been mostly waiting on full release to work on things.

I made a 1.20.6 branch if you wanted to do a PR to that branch for your 1.20.6 build.

I'm fairly interested in seeing how the non HUD mixin works. I have some other bugs to work on already for all versions.

**Comment by Meshiest** [comment]
updated for 1.21-pre4 + did the client mod + hudrendercallback changes more minimally this time

**Pull request merged**
